export const START_USER_CHAT_INIT = "START_USER_CHAT_INIT";
export const START_USER_CHAT_SUCCESS = "START_USER_CHAT_SUCCESS";
export const START_USER_CHAT_FAILURE = "START_USER_CHAT_FAILURE";

export const GET_NEXT_STATEMENT_INIT = "GET_NEXT_STATEMENT_INIT";
export const GET_NEXT_STATEMENT_SUCCESS = "GET_NEXT_STATEMENT_SUCCESS";
export const GET_NEXT_STATEMENT_FAILURE = "GET_NEXT_STATEMENT_FAILURE";

export const GET_CHAT_HISTORY_INIT = "GET_CHAT_HISTORY_INIT";
export const GET_CHAT_HISTORY_SUCCESS = "GET_CHAT_HISTORY_SUCCESS";
export const GET_CHAT_HISTORY_FAILURE = "GET_CHAT_HISTORY_FAILURE";

export const SAVE_AVATAR_PREFERENCE_INIT = "SAVE_AVATAR_PREFERENCE_INIT";
export const SAVE_AVATAR_PREFERENCE_SUCCESS = "SAVE_AVATAR_PREFERENCE_SUCCESS";
export const SAVE_AVATAR_PREFERENCE_FAILURE = "SAVE_AVATAR_PREFERENCE_FAILURE";

export const GET_DATA_POINTS_INIT = "GET_DATA_POINTS_INIT";
export const GET_DATA_POINTS_SUCCESS = "GET_DATA_POINTS_SUCCESS";
export const GET_DATA_POINTS_FAILURE = "GET_DATA_POINTS_FAILURE";

export const CLEAR_USER_CHAT = "CLEAR_USER_CHAT";
export const RESET_USER_CHAT = "RESET_USER_CHAT";